version: '3.1'

services:
  app:
    image: 'wheel:latest'
    container_name: wheel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/wheel
      - SPRING_DATASOURCE_USERNAME=wheel
      - SPRING_DATASOURCE_PASSWORD=wheel

  postgres:
    image: 'postgres:15-alpine'
    container_name: wheelDB
    environment:
      POSTGRES_USER: wheel
      POSTGRES_PASSWORD: wheel
      POSTGRES_DB: wheel
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  postgres-data: